In [1]:
import pandas as pd

In [44]:
df = pd.read_excel('../herballife_raw1.xlsx')

,Business question/issue,Potential Legal issue implicated by business question,Legal professional_1,Legal professional_2,Legal professional_3,Legal professional_4,Legal professional_5
0,Example: We have a stock delay,FTC compliance,Cyrus Moshiri,NaN,NaN,NaN,NaN
1,I have a contract that needs legal review,Contracts,Alaaeddine Sahibi,Patti Sabel,Julie Ting,NaN,NaN
2,I have a document that needs legal review,Contracts,Alaaeddine Sahibi,Julie Ting,NaN,NaN,NaN
3,I have an asset purchase agreement that needs ...,Contracts,Alaaeddine Sahibi,NaN,NaN,NaN,NaN
4,I have an agreement that needs legal review,Contracts,Alaaeddine Sahibi,NaN,NaN,NaN,NaN

In [45]:
df = df.reset_index()

,index,Business question/issue,Potential Legal issue implicated by business question,Legal professional_1,Legal professional_2,Legal professional_3,Legal professional_4,Legal professional_5
0,0,Example: We have a stock delay,FTC compliance,Cyrus Moshiri,NaN,NaN,NaN,NaN
1,1,I have a contract that needs legal review,Contracts,Alaaeddine Sahibi,Patti Sabel,Julie Ting,NaN,NaN
2,2,I have a document that needs legal review,Contracts,Alaaeddine Sahibi,Julie Ting,NaN,NaN,NaN
3,3,I have an asset purchase agreement that needs ...,Contracts,Alaaeddine Sahibi,NaN,NaN,NaN,NaN
4,4,I have an agreement that needs legal review,Contracts,Alaaeddine Sahibi,NaN,NaN,NaN,NaN

In [46]:
df = df.rename(columns={'index':'business_id'})

In [51]:
df = pd.wide_to_long(df, stubnames='Legal professional', i=['business_id','Business question/issue','Potential Legal issue implicated by business question'], j='Name', sep='_')